name: be_focused
description: Focus app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  injectable: ^2.3.2
  icons_plus: ^5.0.0
  gap: ^3.0.1
  injectable_generator: ^2.4.1
  get_it: ^7.6.7
  fpdart: ^1.1.0
  rxdart: 0.27.7
  dartx: ^1.2.0
  timeline_tile: ^2.0.0
  logger: ^2.0.2+1
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.1.0
  awesome_extensions: ^2.0.12
  freezed_annotation: ^2.4.1
  table_calendar: ^3.0.9
  flutter_sticky_header: ^0.6.5
  flutter_animate: ^4.5.0

  # Firebase
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.3

dev_dependencies:
  bloc_test: ^9.1.5
  freezed: ^2.4.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

  build_runner: ^2.4.8
  po_editor_translations: ^0.1.0


flutter:
  uses-material-design: true
  generate: true