name: be_focused
description: Focus app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  logger: ^2.0.2+1
  auto_route: ^7.8.4
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  
  po_editor_translations: ^0.1.0

flutter:
  uses-material-design: true
  generate: true
